server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    # 1. SPECIFIC ROUTE FOR FILE UPLOADS (No Buffering)
    location /api/upload/ {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # Fixes for S3 Signature & buffering issues:
        proxy_request_buffering off;
        proxy_buffering off;
        client_max_body_size 20M;
    }

    # 2. GENERIC API ROUTE (For all other backend requests)
    location /api {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 3. WEBSOCKETS
    location /socket.io {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # 4. FRONTEND SPA ROUTING
    location / {
        try_files $uri $uri/ /index.html;
    }
}